# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"partition_seq1": "Partition.ipynb",
         "partition_seq2": "Partition.ipynb",
         "partition": "Partition.ipynb"}

modules = ["partition.py"]

doc_url = "https://shrestha-pranav.github.io/algorithms/"

git_url = "https://github.com/shrestha-pranav/algorithms/tree/master/"

def custom_doc_links(name): return None
