# AUTOGENERATED! DO NOT EDIT! File to edit: Partition.ipynb (unless otherwise specified).

__all__ = ['partition_seq1', 'partition_seq2', 'partition']

# Cell
import functools

# Cell
def partition_seq1():
    # Alternate between {1, 2, 3, 4, ...} and {3, 5, 7, 9, ...}
    i, j = 1, 3
    while True:
        yield i
        yield j
        i, j = i+1, j+2

def partition_seq2():
    i = 1
    for ddelta in partition_seq1():
        yield i
        i += ddelta

# Cell
@functools.lru_cache(maxsize=1000, typed=True)
def partition(n:int):
    if n < 0: return 0
    elif n == 0: return 1

    delta_gen = partition_seq2()
    total = 0

    while True:
        d = [next(delta_gen) for _ in range(4)]

        total += partition(n - d[0]) + partition(n - d[1])
        total -= partition(n - d[2]) + partition(n - d[3])

        if d[3] > n: break

    return total